# Generated by Django 5.2 on 2025-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("financeiro", "Financeiro"),
                    ("estoque", "Estoque"),
                    ("dev", "Desenvolvimento"),
                ],
                default="estoque",
                max_length=50,
            ),
        ),
    ]
