# Generated by Django 5.2 on 2025-04-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("categoria", models.CharField(max_length=100)),
                ("fornecedor", models.CharField(max_length=100)),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("preco_venda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantidade", models.IntegerField()),
                ("localizacao", models.CharField(max_length=100)),
                ("data_validade", models.DateField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="produtos/"),
                ),
            ],
        ),
    ]
