# Generated by Django 5.2 on 2025-04-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sys", "0002_produto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
